name: micahmoss
favicon: null
layout_spectrum: 0.26081
typography_spectrum: 0.25164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f07818'
    - '#5e412f'
    - '#f0a830'
    - '#fcebb6'
    - '#78c0a8'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: 6cee48dc-dd8c-4a98-9169-13cff52f28e8
    url: null
