typography_spectrum: 0.25
color:
  brandColors:
    - '#f07818'
    - '#5e412f'
    - '#f0a830'
    - '#fcebb6'
    - '#78c0a8'
  brandStrength: 0.125
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: micahmoss
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Micah Moss
description: Writer / Director
purpose: []
